spring:
  cloud:
    stream:
      kafka:
        bindings:
          input1:
            consumer:
              enableDlq: false
              dlqName: test-dlq
              maxPollRecords: 5
              autoCommitOnError: true
          output1:
            producer:
              sync: true
              messageKeyExpression: headers['myKey']
      bindings:
        input1:
          binder: kafka-input
          group: test
          destination: test-topic
          contentType: text/plain
          consumer:
            instanceCount: 10
            headerMode: raw
            partitioned: true
        output1:
          binder: kafka-output
          destination: test-output-topic
          producer:
            headerMode: raw
            useNativeEncoding: true
      binders:
        kafka-input:
          type: kafka
          environment:
            spring:
              cloud:
                stream:
                  kafka:
                    binder:
                      brokers: localhost:9093
                      zkNodes: localhost:2181
        kafka-output:
          type: kafka
          environment:
            spring:
              cloud:
                stream:
                  kafka:
                    binder:
                      minPartitionCount: 3
                      brokers: localhost:9093
                      zkNodes: localhost:2181
server:
  port: 8081